{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": true,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": [
      "manageMessages"
    ]
  },
  "trigger": {
    "type": "label",
    "content": "announce"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;arg1;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);1}}\n{set;arg2;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);2}}\n{set;arg3;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);3}}\n{set;arg4;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);4}}\n{channel.send;{a!ae;--title=\"{get;arg3}\";--description=\"{get;arg4}\";--message=\"{role.mention;{get;arg2}}\"};{get;arg1}}",
      "channel": "658515840588578836",
      "id": "5ed82c208f44120026ab469c"
    }
  ],
  "formatVersion": "1.2"
}