{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": false,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": [
      "manageMessages"
    ]
  },
  "trigger": {
    "type": "label",
    "content": "poll"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{set;arg1;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);1}}\n{set;arg2;{find;{args};(.*?)(?:\\s?)(?:\\|)(?:\\s?)(.*?$);2}}\n{a!ae;--title=\"{get;arg1}\";--description=\"{get;arg2}\";--message=\"{role.mention;role-id-here}\"}\n{message.react;<emoji-id-here>;{channel.lastMessageID}}\n{message.react;<emoji-id-here>;{channel.lastMessageID}}",
      "channel": "716391697331781673",
      "id": "5ede74008f44120026abfced"
    }
  ],
  "formatVersion": "1.2"
}