{
  "meta": "Exported from https://atlasbot.xyz",
  "flags": {
    "ttl": 0,
    "cooldown": 0,
    "enabled": true,
    "silent": false,
    "delete": true,
    "quiet": false
  },
  "restrictions": {
    "mode": "blacklist",
    "roles": [],
    "channels": [],
    "permissions": [
      "kickMembers"
    ]
  },
  "trigger": {
    "type": "label",
    "content": "softwarn"
  },
  "content": [
    {
      "fallback": true,
      "type": "channel",
      "message": "{if;{catch;{user.id;{args;1}};Error};!=;Error;{a!ae;--field1name=\"Reason\";--field1value=\"{args;2;infinity}\";--field1inline;--field2name=\"Operator\";--field2value=\"{user.mention}\";--field2inline;--description=\"{args;1}, you have been soft warned. This means an infraction was not given but you were told by a Staff member to quit with what you are doing.\\n\\nIf you continue, a infraction will be added onto your profile and you will have your first warn.\";--message=\"{user.mention;{args;1}}\"};This is not a valid user, please provide an appropriate user tag.}",
      "id": "5ed833d38f44120026ab4784"
    }
  ],
  "formatVersion": "1.2"
}